version: 2

sources:
  - name: public
    description: "Raw data warehouse tables in public schema"
    database: ecommerce_dw
    schema: public
    
    tables:
      - name: dim_customers
        description: "Customer dimension with location data"
        columns:
          - name: customer_key
            description: "Surrogate key for customers"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Natural key from source system"
            
      - name: dim_products
        description: "Product dimension with attributes"
        columns:
          - name: product_key
            description: "Surrogate key for products"
            tests:
              - unique
              - not_null
              
      - name: dim_date
        description: "Date dimension for time-based analysis"
        
      - name: fact_orders
        description: "Order transaction fact table"
        columns:
          - name: order_key
            description: "Surrogate key for order line items"